package main

// generated by Destructure
type Distance struct {
	distance []int // the longer the better, and the lower the entries the better

	// extra info so we can immediately launch the right function
	fn      Func
	fnScope *FuncScope // scope is filled while distance is calculated

	// keep last eval of args, so we don't we waste computations during dispatch
	args []Value
}
